// <auto-generated>
// Generated by scripts/generate_shared.py. Do not edit by hand.
// Contract SHA-256: b4c581485686d7caeeffc73f0f77ccad719bee372145190b39de39fff050278b
// </auto-generated>
import Foundation

public enum HaloState: String, Codable, Equatable, Sendable, CaseIterable {
    case idle
    case thinking
    case working
    case done
    case attention
    case error
}

public enum ErrorPresentation: String, Codable, Equatable, Sendable, CaseIterable {
    case flashing
    case bright
    case dim
}

public struct SharedStateParameters: Equatable, Sendable {
    public let priority: Int
    public let label: String
    public let red: Double
    public let green: Double
    public let blue: Double
    public let breathPeriod: Double
    public let visualMaximum: Double
    public let visualMinimum: Double
    public let poweredMaximum: Double
    public let poweredMinimum: Double
    public let brightShare: Double
    public let orbitVelocity: Double
    public let envelopePeriod: Double
    public let driftAmplitude: Double
    public let driftPeriod: Double
    public let inertiaDamping: Double
    public let coreWhite: Double
    public let glowGain: Double
}

public enum GeneratedHaloSpec {
    public static let contractVersion = 2
    public static let releaseVersion = "0.14.0"
    public static let specSha256 = "b4c581485686d7caeeffc73f0f77ccad719bee372145190b39de39fff050278b"
    public static let transitionDimEnd = 0.36
    public static let transitionColorBlendEnd = 0.58
    public static let transitionLowPowered = 0.08
    public static let attentionPeriod = 3.35
    public static let attentionFirstCenter = 0.16
    public static let attentionFirstWidth = 0.095
    public static let attentionFirstStrength = 1.0
    public static let attentionSecondCenter = 0.37
    public static let attentionSecondWidth = 0.115
    public static let attentionSecondStrength = 0.82
    public static let attentionLivingBase = 0.12
    public static let attentionLivingAmplitude = 0.065
    public static let attentionLivingPhase = 0.18
    public static let errorBrightPower = 0.92
    public static let errorDimPower = 0.04
    public static let errorFlashPeriod = 1.55
    public static let errorFirstCenter = 0.12
    public static let errorFirstWidth = 0.055
    public static let errorSecondCenter = 0.34
    public static let errorSecondWidth = 0.065
    public static let minimumGapSeparation = 40.0
    public static let maximumGapSeparation = 150.0
    public static let repulsionSpeedMinimum = 14.0
    public static let repulsionSpeedMaximum = 92.0
    public static let repulsionDurationFactor = 1.42
    public static let repulsionReferenceSpeed = 72.0
    public static let repulsionDurationMinimum = 1.28
    public static let repulsionDurationMaximum = 3.05
    public static let exitVelocityScale = 0.42
    public static let exitVelocityMinimum = 9.0
    public static let exitVelocityMaximum = 38.0
    public static let rateLimitMarker = "\"rate_limits\""
    public static let ratePayloadKey = "payload"
    public static let rateInfoKey = "info"
    public static let rateLimitsKey = "rate_limits"
    public static let ratePrimaryKey = "primary"
    public static let rateSecondaryKey = "secondary"
    public static let rateUsedPercentKey = "used_percent"
    public static let rateLimitTailBytes = 1048576
    public static let rateLimitRecentFileCount = 16
    public static let rateLimitRecentLineCount = 300

    private static let taskStartExact: Set<String> = ["task_started", "user_message"]
    private static let taskCompleteExact: Set<String> = ["task_complete"]
    private static let attentionContains: Set<String> = ["approval", "request_user", "needs_input"]
    private static let fatalExact: Set<String> = ["turn_aborted", "turn_failed", "task_failed", "task_cancelled", "task_interrupted", "fatal_error"]
    private static let toolOutputExact: Set<String> = ["function_call_output", "custom_tool_call_output", "tool_search_output"]
    private static let toolCallExact: Set<String> = ["custom_tool_call", "web_search_call", "tool_search_call"]

    public static func state(_ state: HaloState) -> SharedStateParameters {
        switch state {
        case .idle:
            SharedStateParameters(
                priority: 5, label: "OFFLINE",
                red: 113, green: 132, blue: 140,
                breathPeriod: 6.8,
                visualMaximum: 0.4,
                visualMinimum: 0.18,
                poweredMaximum: 0.0,
                poweredMinimum: 0.0,
                brightShare: 0.5,
                orbitVelocity: 27,
                envelopePeriod: 7.6,
                driftAmplitude: 5.2,
                driftPeriod: 4.8,
                inertiaDamping: 0.62,
                coreWhite: 0.82,
                glowGain: 1.0)
        case .thinking:
            SharedStateParameters(
                priority: 3, label: "THINKING",
                red: 226, green: 170, blue: 31,
                breathPeriod: 5.5,
                visualMaximum: 1.0,
                visualMinimum: 0.26,
                poweredMaximum: 1.0,
                poweredMinimum: 0.18,
                brightShare: 0.7,
                orbitVelocity: 78,
                envelopePeriod: 4.2,
                driftAmplitude: 7.0,
                driftPeriod: 3.6,
                inertiaDamping: 0.66,
                coreWhite: 0.9,
                glowGain: 1.13)
        case .working:
            SharedStateParameters(
                priority: 2, label: "EXECUTING",
                red: 39, green: 161, blue: 211,
                breathPeriod: 7.2,
                visualMaximum: 1.0,
                visualMinimum: 0.22,
                poweredMaximum: 1.0,
                poweredMinimum: 0.16,
                brightShare: 0.78,
                orbitVelocity: 106,
                envelopePeriod: 2.2,
                driftAmplitude: 8.5,
                driftPeriod: 2.8,
                inertiaDamping: 0.72,
                coreWhite: 0.86,
                glowGain: 1.07)
        case .done:
            SharedStateParameters(
                priority: 4, label: "COMPLETE",
                red: 38, green: 198, blue: 108,
                breathPeriod: 9.2,
                visualMaximum: 0.92,
                visualMinimum: 0.22,
                poweredMaximum: 0.84,
                poweredMinimum: 0.09,
                brightShare: 0.76,
                orbitVelocity: 38,
                envelopePeriod: 8.5,
                driftAmplitude: 4.2,
                driftPeriod: 5.5,
                inertiaDamping: 0.58,
                coreWhite: 0.84,
                glowGain: 1.0)
        case .attention:
            SharedStateParameters(
                priority: 1, label: "NEEDS YOU",
                red: 142, green: 108, blue: 236,
                breathPeriod: 5.8,
                visualMaximum: 1.0,
                visualMinimum: 0.18,
                poweredMaximum: 1.0,
                poweredMinimum: 0.1,
                brightShare: 0.44,
                orbitVelocity: 46,
                envelopePeriod: 4.1,
                driftAmplitude: 6.5,
                driftPeriod: 3.3,
                inertiaDamping: 0.76,
                coreWhite: 0.82,
                glowGain: 1.0)
        case .error:
            SharedStateParameters(
                priority: 0, label: "INTERRUPTED",
                red: 218, green: 50, blue: 86,
                breathPeriod: 1.55,
                visualMaximum: 1.0,
                visualMinimum: 0.04,
                poweredMaximum: 1.0,
                poweredMinimum: 0.0,
                brightShare: 0.22,
                orbitVelocity: 60,
                envelopePeriod: 1.75,
                driftAmplitude: 7.5,
                driftPeriod: 2.6,
                inertiaDamping: 0.84,
                coreWhite: 0.91,
                glowGain: 1.12)
        }
    }

    public static func transitionDuration(target: HaloState) -> Double {
        switch target {
        case .idle: 1.78
        case .thinking: 1.68
        case .working: 1.48
        case .done: 1.72
        case .attention: 1.02
        case .error: 0.92
        }
    }

    public static func isTaskStartEvent(_ value: String) -> Bool { taskStartExact.contains(value.lowercased()) }
    public static func isTaskCompleteEvent(_ value: String) -> Bool { taskCompleteExact.contains(value.lowercased()) }
    public static func isFatalEvent(_ value: String) -> Bool { fatalExact.contains(value.lowercased()) }
    public static func isToolOutput(_ value: String) -> Bool { toolOutputExact.contains(value.lowercased()) }
    public static func isToolCall(_ value: String) -> Bool { toolCallExact.contains(value.lowercased()) }
    public static func isAttentionEvent(_ value: String) -> Bool {
        containsAny(value.lowercased(), Array(attentionContains))
    }

    public static func friendlyAction(_ raw: String) -> String {
        let value = raw.lowercased()
        if containsAny(value, ["shell", "command"]) { return "Running command" }
        if containsAny(value, ["apply_patch", "edit", "write"]) { return "Editing files" }
        if containsAny(value, ["web_search", "search_query"]) { return "Searching" }
        if containsAny(value, ["tool_search"]) { return "Finding a tool" }
        if containsAny(value, ["browser"]) { return "Using browser" }
        if containsAny(value, ["image"]) { return "Working with image" }
        if containsAny(value, ["plan"]) { return "Updating plan" }
        return "Executing"
    }

    public static func classifyFailure(_ text: String) -> String? {
        let value = text.lowercased()
        if containsAny(value, ["authentication failed", "unauthorized", "invalid token", "sign in again"]) { return "failure.auth_expired" }
        if containsAny(value, ["rate limit reached", "usage limit", "quota exceeded", "rate_limit_reached"]) { return "failure.quota_exhausted" }
        if containsAny(value, ["service unavailable", "server overloaded", "overloaded", "bad gateway"]) { return "failure.service_unavailable" }
        if containsAny(value, ["connection failed", "network error", "connection aborted", "request timed out", "connect timeout"]) { return "failure.connection_failed" }
        return nil
    }

    private static func containsAny(_ value: String, _ choices: [String]) -> Bool {
        choices.contains { value.contains($0) }
    }
}
