// <auto-generated>
// Generated by scripts/generate_shared.py. Do not edit by hand.
// Contract SHA-256: 568c3efbc4da7f7c5ded304afcaefef60b47bb85a05ab909f3e6e5de019e2ef8
// </auto-generated>
using System;
using System.Linq;

namespace CodexHalo
{
    public enum HaloState
    {
        Idle,
        Thinking,
        Working,
        Done,
        Attention,
        Error
    }

    public enum ErrorPresentation
    {
        Flashing,
        Bright,
        Dim
    }

    public sealed class SharedStateParameters
    {
        public readonly int Priority;
        public readonly string Label;
        public readonly byte Red;
        public readonly byte Green;
        public readonly byte Blue;
        public readonly double BreathPeriod;
        public readonly double VisualMaximum;
        public readonly double VisualMinimum;
        public readonly double PoweredMaximum;
        public readonly double PoweredMinimum;
        public readonly double BrightShare;
        public readonly double OrbitVelocity;
        public readonly double EnvelopePeriod;
        public readonly double DriftAmplitude;
        public readonly double DriftPeriod;
        public readonly double InertiaDamping;
        public readonly double CoreWhite;
        public readonly double GlowGain;

        public SharedStateParameters(int priority, string label, byte red, byte green,
            byte blue, double breathPeriod, double visualMaximum, double visualMinimum,
            double poweredMaximum, double poweredMinimum, double brightShare,
            double orbitVelocity, double envelopePeriod, double driftAmplitude,
            double driftPeriod, double inertiaDamping, double coreWhite, double glowGain)
        {
            Priority = priority;
            Label = label;
            Red = red;
            Green = green;
            Blue = blue;
            BreathPeriod = breathPeriod;
            VisualMaximum = visualMaximum;
            VisualMinimum = visualMinimum;
            PoweredMaximum = poweredMaximum;
            PoweredMinimum = poweredMinimum;
            BrightShare = brightShare;
            OrbitVelocity = orbitVelocity;
            EnvelopePeriod = envelopePeriod;
            DriftAmplitude = driftAmplitude;
            DriftPeriod = driftPeriod;
            InertiaDamping = inertiaDamping;
            CoreWhite = coreWhite;
            GlowGain = glowGain;
        }
    }

    public static class GeneratedHaloSpec
    {
        public const int ContractVersion = 2;
        public const string ReleaseVersion = "0.13.0";
        public const string SpecSha256 = "568c3efbc4da7f7c5ded304afcaefef60b47bb85a05ab909f3e6e5de019e2ef8";
        public const double TransitionDimEnd = 0.36;
        public const double TransitionColorBlendEnd = 0.58;
        public const double TransitionLowPowered = 0.08;
        public const double AttentionPeriod = 5.8;
        public const double AttentionFirstCenter = 0.16;
        public const double AttentionFirstWidth = 0.095;
        public const double AttentionFirstStrength = 1.0;
        public const double AttentionSecondCenter = 0.38;
        public const double AttentionSecondWidth = 0.11;
        public const double AttentionSecondStrength = 0.82;
        public const double AttentionLivingBase = 0.08;
        public const double AttentionLivingAmplitude = 0.05;
        public const double AttentionLivingPhase = 0.18;
        public const double ErrorBrightPower = 0.92;
        public const double ErrorDimPower = 0.04;
        public const double ErrorFlashPeriod = 1.55;
        public const double ErrorFirstCenter = 0.12;
        public const double ErrorFirstWidth = 0.055;
        public const double ErrorSecondCenter = 0.34;
        public const double ErrorSecondWidth = 0.065;
        public const double MinimumGapSeparation = 40;
        public const double MaximumGapSeparation = 150;
        public const double RepulsionSpeedMinimum = 14;
        public const double RepulsionSpeedMaximum = 92;
        public const double RepulsionDurationFactor = 1.42;
        public const double RepulsionReferenceSpeed = 72;
        public const double RepulsionDurationMinimum = 1.28;
        public const double RepulsionDurationMaximum = 3.05;
        public const double ExitVelocityScale = 0.42;
        public const double ExitVelocityMinimum = 9;
        public const double ExitVelocityMaximum = 38;
        public const string RateLimitMarker = "\"rate_limits\"";
        public const string RatePayloadKey = "payload";
        public const string RateInfoKey = "info";
        public const string RateLimitsKey = "rate_limits";
        public const string RatePrimaryKey = "primary";
        public const string RateSecondaryKey = "secondary";
        public const string RateUsedPercentKey = "used_percent";
        public const int RateLimitTailBytes = 1048576;
        public const int RateLimitRecentFileCount = 16;
        public const int RateLimitRecentLineCount = 300;

        private static readonly string[] TaskStartExact = new string[] { "task_started", "user_message" };
        private static readonly string[] TaskCompleteExact = new string[] { "task_complete" };
        private static readonly string[] AttentionContains = new string[] { "approval", "request_user", "needs_input" };
        private static readonly string[] FatalExact = new string[] { "turn_aborted", "turn_failed", "task_failed", "task_cancelled", "task_interrupted", "fatal_error" };
        private static readonly string[] ToolOutputExact = new string[] { "function_call_output", "custom_tool_call_output", "tool_search_output" };
        private static readonly string[] ToolCallExact = new string[] { "custom_tool_call", "web_search_call", "tool_search_call" };

        public static SharedStateParameters State(HaloState state)
        {
            switch (state)
            {
                case HaloState.Idle:
                    return new SharedStateParameters(
                        5, "READY",
                        113, 132, 140,
                        6.8, 0.4,
                        0.18, 0.0,
                        0.0, 0.5,
                        27, 7.6,
                        5.2, 4.8,
                        0.62, 0.82,
                        1.0);
                case HaloState.Thinking:
                    return new SharedStateParameters(
                        3, "THINKING",
                        226, 170, 31,
                        5.5, 1.0,
                        0.26, 1.0,
                        0.18, 0.7,
                        78, 4.2,
                        7.0, 3.6,
                        0.66, 0.9,
                        1.13);
                case HaloState.Working:
                    return new SharedStateParameters(
                        2, "EXECUTING",
                        52, 158, 199,
                        7.2, 1.0,
                        0.22, 1.0,
                        0.16, 0.78,
                        106, 2.2,
                        8.5, 2.8,
                        0.72, 0.86,
                        1.07);
                case HaloState.Done:
                    return new SharedStateParameters(
                        4, "COMPLETE",
                        38, 198, 108,
                        9.2, 0.92,
                        0.22, 0.84,
                        0.09, 0.76,
                        38, 8.5,
                        4.2, 5.5,
                        0.58, 0.84,
                        1.0);
                case HaloState.Attention:
                    return new SharedStateParameters(
                        1, "NEEDS YOU",
                        142, 108, 236,
                        5.8, 1.0,
                        0.18, 1.0,
                        0.1, 0.44,
                        46, 4.1,
                        6.5, 3.3,
                        0.76, 0.82,
                        1.0);
                case HaloState.Error:
                    return new SharedStateParameters(
                        0, "INTERRUPTED",
                        218, 50, 86,
                        1.55, 1.0,
                        0.04, 1.0,
                        0.0, 0.22,
                        60, 1.75,
                        7.5, 2.6,
                        0.84, 0.91,
                        1.12);
                default: throw new ArgumentOutOfRangeException("state");
            }
        }

        public static double TransitionDuration(HaloState target)
        {
            switch (target)
            {
                case HaloState.Idle: return 1.78;
                case HaloState.Thinking: return 1.68;
                case HaloState.Working: return 1.48;
                case HaloState.Done: return 1.72;
                case HaloState.Attention: return 1.02;
                case HaloState.Error: return 0.92;
                default: return 1.78;
            }
        }

        public static bool IsTaskStartEvent(string value) { return Exact(value, TaskStartExact); }
        public static bool IsTaskCompleteEvent(string value) { return Exact(value, TaskCompleteExact); }
        public static bool IsFatalEvent(string value) { return Exact(value, FatalExact); }
        public static bool IsToolOutput(string value) { return Exact(value, ToolOutputExact); }
        public static bool IsToolCall(string value) { return Exact(value, ToolCallExact); }
        public static bool IsAttentionEvent(string value)
        {
            return ContainsAny((value ?? String.Empty).ToLowerInvariant(), AttentionContains);
        }

        public static string FriendlyAction(string raw)
        {
            string value = (raw ?? String.Empty).ToLowerInvariant();
            if (ContainsAny(value, new string[] { "shell", "command" })) return "Running command";
            if (ContainsAny(value, new string[] { "apply_patch", "edit", "write" })) return "Editing files";
            if (ContainsAny(value, new string[] { "web_search", "search_query" })) return "Searching";
            if (ContainsAny(value, new string[] { "tool_search" })) return "Finding a tool";
            if (ContainsAny(value, new string[] { "browser" })) return "Using browser";
            if (ContainsAny(value, new string[] { "image" })) return "Working with image";
            if (ContainsAny(value, new string[] { "plan" })) return "Updating plan";
            return "Executing";
        }

        public static string ClassifyFailure(string text)
        {
            string value = (text ?? String.Empty).ToLowerInvariant();
            if (ContainsAny(value, new string[] { "authentication failed", "unauthorized", "invalid token", "sign in again" })) return "认证已失效";
            if (ContainsAny(value, new string[] { "rate limit reached", "usage limit", "quota exceeded", "rate_limit_reached" })) return "额度已用尽";
            if (ContainsAny(value, new string[] { "service unavailable", "server overloaded", "overloaded", "bad gateway" })) return "服务暂时不可用";
            if (ContainsAny(value, new string[] { "connection failed", "network error", "connection aborted", "request timed out", "connect timeout" })) return "连接 Codex 失败";
            return null;
        }

        private static bool Exact(string value, string[] choices)
        {
            string normalized = (value ?? String.Empty).ToLowerInvariant();
            return choices.Contains(normalized);
        }

        private static bool ContainsAny(string value, string[] choices)
        {
            return choices.Any(delegate(string choice)
            {
                return value.IndexOf(choice, StringComparison.Ordinal) >= 0;
            });
        }
    }
}
